name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with: 
        python-version: 3.9
        cache: 'pip'
    - name: Install Pipenv
      run: pip install pipenv
    - name: Create Sphinx Dependencies
      run: pipenv requirements --dev > ./docs/requirements.txt
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        python_version: 3.9
        sphinx_version: 7.2.6
        documentation_path: ./docs/source
        cache: true
        checkout: true
        publish: true