name: Deploy Sphinx documentation to Pages

on:
  push:
    # branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    permissions:
      pages: write
      id-token: write
    steps:

    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.22"
    
    - name: Set up Python
      run: uv python install 3.9

    - name: Generate Dev Requirements
      run: uv pip freeze > dev-requirements.txt

    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        checkout: false
        documentation_path: ./docs/source
        requirements_path: ./dev-requirements.txt
        cache: true
        publish: true